import React, {type FC} from 'react';
import {Text, TouchableOpacity, View, FlatList} from 'react-native';
import Icon from 'react-native-vector-icons/FontAwesome';
import DataTableComponent from '../../Components/DataTableComponent/DataTableComponent';
import SelectLineModal from '../SelectLineModal/SelectLineModal';
import CustomSubmitButton from '../CustomSubmitButton/CustomSubmitButton';
import CustomModalButton from '../CustomModalButton/CustomModalButton';
import Styles from './style';

const ReceiveTab: FC = () => {
  const [selectedLine, setSelectedLine] = React.useState<string>('');
  const [lineModalVisible, setLineModalVisible] = React.useState(false);

  const orgTreeData = [
    {
      id: 352,
      name: 'Root',
      rootPath: '/Root',
      children: [
        {
          id: 5730,
          parentId: 352,
          parent: 352,
          parentName: 'Root',
          name: '4A Yarn Dyeing Ltd',
          rootPath: '/4A Yarn Dyeing Ltd',
          children: [
            {
              id: 5731,
              parentId: 5730,
              parent: 5730,
              parentName: '4A Yarn Dyeing Ltd',
              name: '4A-1 1ST',
              rootPath: '/4A Yarn Dyeing Ltd/4A-1 1ST',
              children: [
                {
                  id: 5732,
                  parentId: 5731,
                  parent: 5731,
                  parentName: '4A-1 1ST',
                  name: '4A-1-01',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-1 1ST/4A-1-01',
                  children: [],
                },
                {
                  id: 5733,
                  parentId: 5731,
                  parent: 5731,
                  parentName: '4A-1 1ST',
                  name: '4A-1-02',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-1 1ST/4A-1-02',
                  children: [],
                },
                {
                  id: 5734,
                  parentId: 5731,
                  parent: 5731,
                  parentName: '4A-1 1ST',
                  name: '4A-1-03',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-1 1ST/4A-1-03',
                  children: [],
                },
                {
                  id: 5735,
                  parentId: 5731,
                  parent: 5731,
                  parentName: '4A-1 1ST',
                  name: '4A-1-04',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-1 1ST/4A-1-04',
                  children: [],
                },
                {
                  id: 5736,
                  parentId: 5731,
                  parent: 5731,
                  parentName: '4A-1 1ST',
                  name: '4A-1-05',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-1 1ST/4A-1-05',
                  children: [],
                },
                {
                  id: 5737,
                  parentId: 5731,
                  parent: 5731,
                  parentName: '4A-1 1ST',
                  name: '4A-1-06',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-1 1ST/4A-1-06',
                  children: [],
                },
              ],
            },
            {
              id: 5738,
              parentId: 5730,
              parent: 5730,
              parentName: '4A Yarn Dyeing Ltd',
              name: '4A-1 2ND',
              rootPath: '/4A Yarn Dyeing Ltd/4A-1 2ND',
              children: [
                {
                  id: 5744,
                  parentId: 5738,
                  parent: 5738,
                  parentName: '4A-1 2ND',
                  name: '4A-1-07',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-1 2ND/4A-1-07',
                  children: [],
                },
                {
                  id: 5739,
                  parentId: 5738,
                  parent: 5738,
                  parentName: '4A-1 2ND',
                  name: '4A-1-08',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-1 2ND/4A-1-08',
                  children: [],
                },
                {
                  id: 5740,
                  parentId: 5738,
                  parent: 5738,
                  parentName: '4A-1 2ND',
                  name: '4A-1-09',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-1 2ND/4A-1-09',
                  children: [],
                },
                {
                  id: 5741,
                  parentId: 5738,
                  parent: 5738,
                  parentName: '4A-1 2ND',
                  name: '4A-1-10',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-1 2ND/4A-1-10',
                  children: [],
                },
                {
                  id: 5742,
                  parentId: 5738,
                  parent: 5738,
                  parentName: '4A-1 2ND',
                  name: '4A-1-11',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-1 2ND/4A-1-11',
                  children: [],
                },
                {
                  id: 5743,
                  parentId: 5738,
                  parent: 5738,
                  parentName: '4A-1 2ND',
                  name: '4A-1-12',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-1 2ND/4A-1-12',
                  children: [],
                },
              ],
            },
            {
              id: 5745,
              parentId: 5730,
              parent: 5730,
              parentName: '4A Yarn Dyeing Ltd',
              name: '4A-1 3RD',
              rootPath: '/4A Yarn Dyeing Ltd/4A-1 3RD',
              children: [
                {
                  id: 5748,
                  parentId: 5745,
                  parent: 5745,
                  parentName: '4A-1 3RD',
                  name: '4A-1-13',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-1 3RD/4A-1-13',
                  children: [],
                },
                {
                  id: 5749,
                  parentId: 5745,
                  parent: 5745,
                  parentName: '4A-1 3RD',
                  name: '4A-1-14',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-1 3RD/4A-1-14',
                  children: [],
                },
                {
                  id: 5750,
                  parentId: 5745,
                  parent: 5745,
                  parentName: '4A-1 3RD',
                  name: '4A-1-15',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-1 3RD/4A-1-15',
                  children: [],
                },
                {
                  id: 5751,
                  parentId: 5745,
                  parent: 5745,
                  parentName: '4A-1 3RD',
                  name: '4A-1-16',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-1 3RD/4A-1-16',
                  children: [],
                },
                {
                  id: 5746,
                  parentId: 5745,
                  parent: 5745,
                  parentName: '4A-1 3RD',
                  name: '4A-1-17',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-1 3RD/4A-1-17',
                  children: [],
                },
                {
                  id: 5747,
                  parentId: 5745,
                  parent: 5745,
                  parentName: '4A-1 3RD',
                  name: '4A-1-18',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-1 3RD/4A-1-18',
                  children: [],
                },
              ],
            },
            {
              id: 5769,
              parentId: 5730,
              parent: 5730,
              parentName: '4A Yarn Dyeing Ltd',
              name: '4A-2 1ST',
              rootPath: '/4A Yarn Dyeing Ltd/4A-2 1ST',
              children: [
                {
                  id: 5770,
                  parentId: 5769,
                  parent: 5769,
                  parentName: '4A-2 1ST',
                  name: '4A-2-01',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 1ST/4A-2-01',
                  children: [],
                },
                {
                  id: 5771,
                  parentId: 5769,
                  parent: 5769,
                  parentName: '4A-2 1ST',
                  name: '4A-2-02',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 1ST/4A-2-02',
                  children: [],
                },
                {
                  id: 5772,
                  parentId: 5769,
                  parent: 5769,
                  parentName: '4A-2 1ST',
                  name: '4A-2-03',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 1ST/4A-2-03',
                  children: [],
                },
                {
                  id: 5773,
                  parentId: 5769,
                  parent: 5769,
                  parentName: '4A-2 1ST',
                  name: '4A-2-04',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 1ST/4A-2-04',
                  children: [],
                },
                {
                  id: 5774,
                  parentId: 5769,
                  parent: 5769,
                  parentName: '4A-2 1ST',
                  name: '4A-2-05',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 1ST/4A-2-05',
                  children: [],
                },
                {
                  id: 5775,
                  parentId: 5769,
                  parent: 5769,
                  parentName: '4A-2 1ST',
                  name: '4A-2-06',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 1ST/4A-2-06',
                  children: [],
                },
                {
                  id: 5776,
                  parentId: 5769,
                  parent: 5769,
                  parentName: '4A-2 1ST',
                  name: '4A-2-07',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 1ST/4A-2-07',
                  children: [],
                },
                {
                  id: 5777,
                  parentId: 5769,
                  parent: 5769,
                  parentName: '4A-2 1ST',
                  name: '4A-2-08',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 1ST/4A-2-08',
                  children: [],
                },
                {
                  id: 5778,
                  parentId: 5769,
                  parent: 5769,
                  parentName: '4A-2 1ST',
                  name: '4A-2-09',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 1ST/4A-2-09',
                  children: [],
                },
                {
                  id: 5779,
                  parentId: 5769,
                  parent: 5769,
                  parentName: '4A-2 1ST',
                  name: '4A-2-10',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 1ST/4A-2-10',
                  children: [],
                },
                {
                  id: 5780,
                  parentId: 5769,
                  parent: 5769,
                  parentName: '4A-2 1ST',
                  name: '4A-2-11',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 1ST/4A-2-11',
                  children: [],
                },
                {
                  id: 5781,
                  parentId: 5769,
                  parent: 5769,
                  parentName: '4A-2 1ST',
                  name: '4A-2-12',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 1ST/4A-2-12',
                  children: [],
                },
                {
                  id: 5782,
                  parentId: 5769,
                  parent: 5769,
                  parentName: '4A-2 1ST',
                  name: '4A-2-13',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 1ST/4A-2-13',
                  children: [],
                },
                {
                  id: 5783,
                  parentId: 5769,
                  parent: 5769,
                  parentName: '4A-2 1ST',
                  name: '4A-2-14',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 1ST/4A-2-14',
                  children: [],
                },
                {
                  id: 5784,
                  parentId: 5769,
                  parent: 5769,
                  parentName: '4A-2 1ST',
                  name: '4A-2-15',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 1ST/4A-2-15',
                  children: [],
                },
                {
                  id: 5785,
                  parentId: 5769,
                  parent: 5769,
                  parentName: '4A-2 1ST',
                  name: '4A-2-16',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 1ST/4A-2-16',
                  children: [],
                },
              ],
            },
            {
              id: 5752,
              parentId: 5730,
              parent: 5730,
              parentName: '4A Yarn Dyeing Ltd',
              name: '4A-2 3RD',
              rootPath: '/4A Yarn Dyeing Ltd/4A-2 3RD',
              children: [
                {
                  id: 5753,
                  parentId: 5752,
                  parent: 5752,
                  parentName: '4A-2 3RD',
                  name: '4A-2-17',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 3RD/4A-2-17',
                  children: [],
                },
                {
                  id: 5754,
                  parentId: 5752,
                  parent: 5752,
                  parentName: '4A-2 3RD',
                  name: '4A-2-18',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 3RD/4A-2-18',
                  children: [],
                },
                {
                  id: 5755,
                  parentId: 5752,
                  parent: 5752,
                  parentName: '4A-2 3RD',
                  name: '4A-2-19',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 3RD/4A-2-19',
                  children: [],
                },
                {
                  id: 5756,
                  parentId: 5752,
                  parent: 5752,
                  parentName: '4A-2 3RD',
                  name: '4A-2-20',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 3RD/4A-2-20',
                  children: [],
                },
                {
                  id: 5757,
                  parentId: 5752,
                  parent: 5752,
                  parentName: '4A-2 3RD',
                  name: '4A-2-21',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 3RD/4A-2-21',
                  children: [],
                },
                {
                  id: 5758,
                  parentId: 5752,
                  parent: 5752,
                  parentName: '4A-2 3RD',
                  name: '4A-2-22',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 3RD/4A-2-22',
                  children: [],
                },
                {
                  id: 5759,
                  parentId: 5752,
                  parent: 5752,
                  parentName: '4A-2 3RD',
                  name: '4A-2-23',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 3RD/4A-2-23',
                  children: [],
                },
                {
                  id: 5760,
                  parentId: 5752,
                  parent: 5752,
                  parentName: '4A-2 3RD',
                  name: '4A-2-24',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 3RD/4A-2-24',
                  children: [],
                },
                {
                  id: 5761,
                  parentId: 5752,
                  parent: 5752,
                  parentName: '4A-2 3RD',
                  name: '4A-2-25',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 3RD/4A-2-25',
                  children: [],
                },
                {
                  id: 5762,
                  parentId: 5752,
                  parent: 5752,
                  parentName: '4A-2 3RD',
                  name: '4A-2-26',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 3RD/4A-2-26',
                  children: [],
                },
                {
                  id: 5763,
                  parentId: 5752,
                  parent: 5752,
                  parentName: '4A-2 3RD',
                  name: '4A-2-27',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 3RD/4A-2-27',
                  children: [],
                },
                {
                  id: 5764,
                  parentId: 5752,
                  parent: 5752,
                  parentName: '4A-2 3RD',
                  name: '4A-2-28',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 3RD/4A-2-28',
                  children: [],
                },
                {
                  id: 5765,
                  parentId: 5752,
                  parent: 5752,
                  parentName: '4A-2 3RD',
                  name: '4A-2-29',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 3RD/4A-2-29',
                  children: [],
                },
                {
                  id: 5766,
                  parentId: 5752,
                  parent: 5752,
                  parentName: '4A-2 3RD',
                  name: '4A-2-30',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 3RD/4A-2-30',
                  children: [],
                },
                {
                  id: 5767,
                  parentId: 5752,
                  parent: 5752,
                  parentName: '4A-2 3RD',
                  name: '4A-2-31',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 3RD/4A-2-31',
                  children: [],
                },
                {
                  id: 5768,
                  parentId: 5752,
                  parent: 5752,
                  parentName: '4A-2 3RD',
                  name: '4A-2-32',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 3RD/4A-2-32',
                  children: [],
                },
              ],
            },
            {
              id: 5786,
              parentId: 5730,
              parent: 5730,
              parentName: '4A Yarn Dyeing Ltd',
              name: '4A-2 4TH',
              rootPath: '/4A Yarn Dyeing Ltd/4A-2 4TH',
              children: [
                {
                  id: 5787,
                  parentId: 5786,
                  parent: 5786,
                  parentName: '4A-2 4TH',
                  name: '4A-2-33',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 4TH/4A-2-33',
                  children: [],
                },
                {
                  id: 5788,
                  parentId: 5786,
                  parent: 5786,
                  parentName: '4A-2 4TH',
                  name: '4A-2-34',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 4TH/4A-2-34',
                  children: [],
                },
                {
                  id: 5789,
                  parentId: 5786,
                  parent: 5786,
                  parentName: '4A-2 4TH',
                  name: '4A-2-35',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 4TH/4A-2-35',
                  children: [],
                },
                {
                  id: 5790,
                  parentId: 5786,
                  parent: 5786,
                  parentName: '4A-2 4TH',
                  name: '4A-2-36',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 4TH/4A-2-36',
                  children: [],
                },
                {
                  id: 5791,
                  parentId: 5786,
                  parent: 5786,
                  parentName: '4A-2 4TH',
                  name: '4A-2-37',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 4TH/4A-2-37',
                  children: [],
                },
                {
                  id: 5792,
                  parentId: 5786,
                  parent: 5786,
                  parentName: '4A-2 4TH',
                  name: '4A-2-38',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 4TH/4A-2-38',
                  children: [],
                },
                {
                  id: 5793,
                  parentId: 5786,
                  parent: 5786,
                  parentName: '4A-2 4TH',
                  name: '4A-2-39',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 4TH/4A-2-39',
                  children: [],
                },
                {
                  id: 5794,
                  parentId: 5786,
                  parent: 5786,
                  parentName: '4A-2 4TH',
                  name: '4A-2-40',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 4TH/4A-2-40',
                  children: [],
                },
                {
                  id: 5795,
                  parentId: 5786,
                  parent: 5786,
                  parentName: '4A-2 4TH',
                  name: '4A-2-41',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 4TH/4A-2-41',
                  children: [],
                },
                {
                  id: 5796,
                  parentId: 5786,
                  parent: 5786,
                  parentName: '4A-2 4TH',
                  name: '4A-2-42',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 4TH/4A-2-42',
                  children: [],
                },
                {
                  id: 5797,
                  parentId: 5786,
                  parent: 5786,
                  parentName: '4A-2 4TH',
                  name: '4A-2-43',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 4TH/4A-2-43',
                  children: [],
                },
                {
                  id: 5798,
                  parentId: 5786,
                  parent: 5786,
                  parentName: '4A-2 4TH',
                  name: '4A-2-44',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 4TH/4A-2-44',
                  children: [],
                },
                {
                  id: 5799,
                  parentId: 5786,
                  parent: 5786,
                  parentName: '4A-2 4TH',
                  name: '4A-2-45',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 4TH/4A-2-45',
                  children: [],
                },
                {
                  id: 5800,
                  parentId: 5786,
                  parent: 5786,
                  parentName: '4A-2 4TH',
                  name: '4A-2-46',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 4TH/4A-2-46',
                  children: [],
                },
                {
                  id: 5801,
                  parentId: 5786,
                  parent: 5786,
                  parentName: '4A-2 4TH',
                  name: '4A-2-47',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 4TH/4A-2-47',
                  children: [],
                },
                {
                  id: 5802,
                  parentId: 5786,
                  parent: 5786,
                  parentName: '4A-2 4TH',
                  name: '4A-2-48',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 4TH/4A-2-48',
                  children: [],
                },
              ],
            },
            {
              id: 5803,
              parentId: 5730,
              parent: 5730,
              parentName: '4A Yarn Dyeing Ltd',
              name: '4A-2 5TH',
              rootPath: '/4A Yarn Dyeing Ltd/4A-2 5TH',
              children: [
                {
                  id: 5804,
                  parentId: 5803,
                  parent: 5803,
                  parentName: '4A-2 5TH',
                  name: '4A-2-49',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 5TH/4A-2-49',
                  children: [],
                },
                {
                  id: 5805,
                  parentId: 5803,
                  parent: 5803,
                  parentName: '4A-2 5TH',
                  name: '4A-2-50',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 5TH/4A-2-50',
                  children: [],
                },
                {
                  id: 5806,
                  parentId: 5803,
                  parent: 5803,
                  parentName: '4A-2 5TH',
                  name: '4A-2-51',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 5TH/4A-2-51',
                  children: [],
                },
                {
                  id: 5807,
                  parentId: 5803,
                  parent: 5803,
                  parentName: '4A-2 5TH',
                  name: '4A-2-52',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 5TH/4A-2-52',
                  children: [],
                },
                {
                  id: 5808,
                  parentId: 5803,
                  parent: 5803,
                  parentName: '4A-2 5TH',
                  name: '4A-2-53',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 5TH/4A-2-53',
                  children: [],
                },
                {
                  id: 5809,
                  parentId: 5803,
                  parent: 5803,
                  parentName: '4A-2 5TH',
                  name: '4A-2-54',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 5TH/4A-2-54',
                  children: [],
                },
                {
                  id: 5810,
                  parentId: 5803,
                  parent: 5803,
                  parentName: '4A-2 5TH',
                  name: '4A-2-55',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 5TH/4A-2-55',
                  children: [],
                },
                {
                  id: 5811,
                  parentId: 5803,
                  parent: 5803,
                  parentName: '4A-2 5TH',
                  name: '4A-2-56',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 5TH/4A-2-56',
                  children: [],
                },
                {
                  id: 5812,
                  parentId: 5803,
                  parent: 5803,
                  parentName: '4A-2 5TH',
                  name: '4A-2-57',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 5TH/4A-2-57',
                  children: [],
                },
                {
                  id: 5813,
                  parentId: 5803,
                  parent: 5803,
                  parentName: '4A-2 5TH',
                  name: '4A-2-58',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 5TH/4A-2-58',
                  children: [],
                },
                {
                  id: 5814,
                  parentId: 5803,
                  parent: 5803,
                  parentName: '4A-2 5TH',
                  name: '4A-2-59',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 5TH/4A-2-59',
                  children: [],
                },
                {
                  id: 5815,
                  parentId: 5803,
                  parent: 5803,
                  parentName: '4A-2 5TH',
                  name: '4A-2-60',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 5TH/4A-2-60',
                  children: [],
                },
                {
                  id: 5816,
                  parentId: 5803,
                  parent: 5803,
                  parentName: '4A-2 5TH',
                  name: '4A-2-61',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 5TH/4A-2-61',
                  children: [],
                },
                {
                  id: 5817,
                  parentId: 5803,
                  parent: 5803,
                  parentName: '4A-2 5TH',
                  name: '4A-2-62',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 5TH/4A-2-62',
                  children: [],
                },
                {
                  id: 5818,
                  parentId: 5803,
                  parent: 5803,
                  parentName: '4A-2 5TH',
                  name: '4A-2-63',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 5TH/4A-2-63',
                  children: [],
                },
                {
                  id: 5819,
                  parentId: 5803,
                  parent: 5803,
                  parentName: '4A-2 5TH',
                  name: '4A-2-64',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 5TH/4A-2-64',
                  children: [],
                },
                {
                  id: 5820,
                  parentId: 5803,
                  parent: 5803,
                  parentName: '4A-2 5TH',
                  name: '4A-2-65',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 5TH/4A-2-65',
                  children: [],
                },
                {
                  id: 5821,
                  parentId: 5803,
                  parent: 5803,
                  parentName: '4A-2 5TH',
                  name: '4A-2-66',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 5TH/4A-2-66',
                  children: [],
                },
              ],
            },
            {
              id: 5822,
              parentId: 5730,
              parent: 5730,
              parentName: '4A Yarn Dyeing Ltd',
              name: '4A-2 6TH',
              rootPath: '/4A Yarn Dyeing Ltd/4A-2 6TH',
              children: [
                {
                  id: 5823,
                  parentId: 5822,
                  parent: 5822,
                  parentName: '4A-2 6TH',
                  name: 'Sample 1+2+3',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 6TH/Sample 1+2+3',
                  children: [],
                },
                {
                  id: 5824,
                  parentId: 5822,
                  parent: 5822,
                  parentName: '4A-2 6TH',
                  name: 'Sample 4+5+6',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 6TH/Sample 4+5+6',
                  children: [],
                },
                {
                  id: 5825,
                  parentId: 5822,
                  parent: 5822,
                  parentName: '4A-2 6TH',
                  name: 'Sample 7+8+9',
                  rootPath: '/4A Yarn Dyeing Ltd/4A-2 6TH/Sample 7+8+9',
                  children: [],
                },
              ],
            },
            {
              id: 6104,
              parentId: 5730,
              parent: 5730,
              parentName: '4A Yarn Dyeing Ltd',
              name: 'Test',
              rootPath: '/4A Yarn Dyeing Ltd/Test',
              children: [],
            },
            {
              id: 6152,
              parentId: 5730,
              parent: 5730,
              parentName: '4A Yarn Dyeing Ltd',
              name: 'Test 33',
              rootPath: '/4A Yarn Dyeing Ltd/Test 33',
              children: [],
            },
            {
              id: 6252,
              parentId: 5730,
              parent: 5730,
              parentName: '4A Yarn Dyeing Ltd',
              name: 'Test Org 1',
              rootPath: '/4A Yarn Dyeing Ltd/Test Org 1',
              children: [],
            },
            {
              id: 6105,
              parentId: 5730,
              parent: 5730,
              parentName: '4A Yarn Dyeing Ltd',
              name: 'Test Org 2',
              rootPath: '/4A Yarn Dyeing Ltd/Test Org 2',
              children: [],
            },
            {
              id: 6106,
              parentId: 5730,
              parent: 5730,
              parentName: '4A Yarn Dyeing Ltd',
              name: 'Test org 3',
              rootPath: '/4A Yarn Dyeing Ltd/Test org 3',
              children: [],
            },
            {
              id: 2123,
              parentId: 5730,
              parent: 5730,
              parentName: '4A Yarn Dyeing Ltd',
              name: 'Test org 4',
              rootPath: '/4A Yarn Dyeing Ltd/Test org 4',
              children: [],
            },
            {
              id: 6102,
              parentId: 5730,
              parent: 5730,
              parentName: '4A Yarn Dyeing Ltd',
              name: 'Test Org Entry',
              rootPath: '/4A Yarn Dyeing Ltd/Test Org Entry',
              children: [],
            },
            {
              id: 6103,
              parentId: 5730,
              parent: 5730,
              parentName: '4A Yarn Dyeing Ltd',
              name: 'Test org ENtry 2',
              rootPath: '/4A Yarn Dyeing Ltd/Test org ENtry 2',
              children: [],
            },
            {
              id: 6202,
              parentId: 5730,
              parent: 5730,
              parentName: '4A Yarn Dyeing Ltd',
              name: 'Test Org PO',
              rootPath: '/4A Yarn Dyeing Ltd/Test Org PO',
              children: [],
            },
            {
              id: 6002,
              parentId: 5730,
              parent: 5730,
              parentName: '4A Yarn Dyeing Ltd',
              name: 'TestOrg1',
              rootPath: '/4A Yarn Dyeing Ltd/TestOrg1',
              children: [],
            },
            {
              id: 6352,
              parentId: 5730,
              parent: 5730,
              parentName: '4A Yarn Dyeing Ltd',
              name: 'TestOrg2',
              rootPath: '/4A Yarn Dyeing Ltd/TestOrg2',
              children: [],
            },
            {
              id: 6353,
              parentId: 5730,
              parent: 5730,
              parentName: '4A Yarn Dyeing Ltd',
              name: 'TestOrg3',
              rootPath: '/4A Yarn Dyeing Ltd/TestOrg3',
              children: [],
            },
          ],
        },
        {
          id: 2002,
          parentId: 352,
          parent: 352,
          parentName: 'Root',
          name: 'App Test 123',
          rootPath: '/Root/App Test 1234',
          children: [],
        },
        {
          id: 6602,
          parentId: 352,
          parent: 352,
          parentName: 'Root',
          name: 'Aqua Diamond ',
          rootPath: '/Root/Aqua Diamond ',
          children: [],
        },
        {
          id: 5699,
          parentId: 352,
          parent: 352,
          parentName: 'Root',
          name: 'Brothers Fashion Ltd.',
          rootPath: '/Brothers Fashion Ltd.',
          children: [
            {
              id: 5700,
              parentId: 5699,
              parent: 5699,
              parentName: 'Brothers Fashion Ltd.',
              name: '2ND FLOOR',
              rootPath: '/Brothers Fashion Ltd./2ND FLOOR',
              children: [
                {
                  id: 5701,
                  parentId: 5700,
                  parent: 5700,
                  parentName: '2ND FLOOR',
                  name: 'BR L01',
                  rootPath: '/Brothers Fashion Ltd./2ND FLOOR/BR L01',
                  children: [],
                },
                {
                  id: 5702,
                  parentId: 5700,
                  parent: 5700,
                  parentName: '2ND FLOOR',
                  name: 'BR L02',
                  rootPath: '/Brothers Fashion Ltd./2ND FLOOR/BR L02',
                  children: [],
                },
                {
                  id: 5703,
                  parentId: 5700,
                  parent: 5700,
                  parentName: '2ND FLOOR',
                  name: 'BR L03',
                  rootPath: '/Brothers Fashion Ltd./2ND FLOOR/BR L03',
                  children: [],
                },
                {
                  id: 5704,
                  parentId: 5700,
                  parent: 5700,
                  parentName: '2ND FLOOR',
                  name: 'BR L04',
                  rootPath: '/Brothers Fashion Ltd./2ND FLOOR/BR L04',
                  children: [],
                },
                {
                  id: 5705,
                  parentId: 5700,
                  parent: 5700,
                  parentName: '2ND FLOOR',
                  name: 'BR L05',
                  rootPath: '/Brothers Fashion Ltd./2ND FLOOR/BR L05',
                  children: [],
                },
                {
                  id: 6253,
                  parentId: 5700,
                  parent: 5700,
                  parentName: '2ND FLOOR',
                  name: 'root test',
                  rootPath: '/Brothers Fashion Ltd./2ND FLOOR/root test',
                  children: [],
                },
                {
                  id: 6254,
                  parentId: 5700,
                  parent: 5700,
                  parentName: '2ND FLOOR',
                  name: 'root test 2',
                  rootPath: '/Brothers Fashion Ltd./2ND FLOOR/root test 2',
                  children: [],
                },
                {
                  id: 6502,
                  parentId: 5700,
                  parent: 5700,
                  parentName: '2ND FLOOR',
                  name: 'Test org 10',
                  rootPath: '/Brothers Fashion Ltd./2ND FLOOR/Test org 10',
                  children: [],
                },
                {
                  id: 6003,
                  parentId: 5700,
                  parent: 5700,
                  parentName: '2ND FLOOR',
                  name: 'Test org 101',
                  rootPath: '/Brothers Fashion Ltd./2ND FLOOR/Test org 101',
                  children: [],
                },
                {
                  id: 6503,
                  parentId: 5700,
                  parent: 5700,
                  parentName: '2ND FLOOR',
                  name: 'Test org 11',
                  rootPath: '/Brothers Fashion Ltd./2ND FLOOR/Test org 11',
                  children: [],
                },
                {
                  id: 6504,
                  parentId: 5700,
                  parent: 5700,
                  parentName: '2ND FLOOR',
                  name: 'Test Org 12',
                  rootPath: '/Brothers Fashion Ltd./2ND FLOOR/Test Org 12',
                  children: [],
                },
                {
                  id: 6452,
                  parentId: 5700,
                  parent: 5700,
                  parentName: '2ND FLOOR',
                  name: 'Test Org 7',
                  rootPath: '/Brothers Fashion Ltd./2ND FLOOR/Test Org 7',
                  children: [],
                },
                {
                  id: 6453,
                  parentId: 5700,
                  parent: 5700,
                  parentName: '2ND FLOOR',
                  name: 'Test Org 8',
                  rootPath: '/Brothers Fashion Ltd./2ND FLOOR/Test Org 8',
                  children: [],
                },
                {
                  id: 6005,
                  parentId: 5700,
                  parent: 5700,
                  parentName: '2ND FLOOR',
                  name: 'TV-Line1',
                  rootPath: '/Brothers Fashion Ltd./2ND FLOOR/TV-Line1',
                  children: [],
                },
              ],
            },
            {
              id: 5706,
              parentId: 5699,
              parent: 5699,
              parentName: 'Brothers Fashion Ltd.',
              name: '3RD FLOOR',
              rootPath: '/Brothers Fashion Ltd./3RD FLOOR',
              children: [
                {
                  id: 5707,
                  parentId: 5706,
                  parent: 5706,
                  parentName: '3RD FLOOR',
                  name: 'BR L06',
                  rootPath: '/Brothers Fashion Ltd./3RD FLOOR/BR L06',
                  children: [],
                },
                {
                  id: 5708,
                  parentId: 5706,
                  parent: 5706,
                  parentName: '3RD FLOOR',
                  name: 'BR L07',
                  rootPath: '/Brothers Fashion Ltd./3RD FLOOR/BR L07',
                  children: [],
                },
                {
                  id: 5709,
                  parentId: 5706,
                  parent: 5706,
                  parentName: '3RD FLOOR',
                  name: 'BR L08',
                  rootPath: '/Brothers Fashion Ltd./3RD FLOOR/BR L08',
                  children: [],
                },
                {
                  id: 5710,
                  parentId: 5706,
                  parent: 5706,
                  parentName: '3RD FLOOR',
                  name: 'BR L09',
                  rootPath: '/Brothers Fashion Ltd./3RD FLOOR/BR L09',
                  children: [],
                },
                {
                  id: 5711,
                  parentId: 5706,
                  parent: 5706,
                  parentName: '3RD FLOOR',
                  name: 'BR L10',
                  rootPath: '/Brothers Fashion Ltd./3RD FLOOR/BR L10',
                  children: [],
                },
              ],
            },
            {
              id: 5712,
              parentId: 5699,
              parent: 5699,
              parentName: 'Brothers Fashion Ltd.',
              name: '4TH FLOOR',
              rootPath: '/Brothers Fashion Ltd./4TH FLOOR',
              children: [
                {
                  id: 5714,
                  parentId: 5712,
                  parent: 5712,
                  parentName: '4TH FLOOR',
                  name: 'BR L11',
                  rootPath: '/Brothers Fashion Ltd./4TH FLOOR/BR L11',
                  children: [],
                },
                {
                  id: 5715,
                  parentId: 5712,
                  parent: 5712,
                  parentName: '4TH FLOOR',
                  name: 'BR L12',
                  rootPath: '/Brothers Fashion Ltd./4TH FLOOR/BR L12',
                  children: [],
                },
                {
                  id: 5716,
                  parentId: 5712,
                  parent: 5712,
                  parentName: '4TH FLOOR',
                  name: 'BR L13',
                  rootPath: '/Brothers Fashion Ltd./4TH FLOOR/BR L13',
                  children: [],
                },
                {
                  id: 5717,
                  parentId: 5712,
                  parent: 5712,
                  parentName: '4TH FLOOR',
                  name: 'BR L14',
                  rootPath: '/Brothers Fashion Ltd./4TH FLOOR/BR L14',
                  children: [],
                },
                {
                  id: 5718,
                  parentId: 5712,
                  parent: 5712,
                  parentName: '4TH FLOOR',
                  name: 'BR L15',
                  rootPath: '/Brothers Fashion Ltd./4TH FLOOR/BR L15',
                  children: [],
                },
                {
                  id: 5713,
                  parentId: 5712,
                  parent: 5712,
                  parentName: '4TH FLOOR',
                  name: 'BR L16',
                  rootPath: '/Brothers Fashion Ltd./4TH FLOOR/BR L16',
                  children: [],
                },
              ],
            },
          ],
        },
        {
          id: 5719,
          parentId: 352,
          parent: 352,
          parentName: 'Root',
          name: 'C. B. M. International Limited',
          rootPath: '/C. B. M. International Limited',
          children: [
            {
              id: 5720,
              parentId: 5719,
              parent: 5719,
              parentName: 'C. B. M. International Limited',
              name: 'SEWING',
              rootPath: '/C. B. M. International Limited/SEWING',
              children: [
                {
                  id: 5722,
                  parentId: 5720,
                  parent: 5720,
                  parentName: 'SEWING',
                  name: 'CB L-A',
                  rootPath: '/C. B. M. International Limited/SEWING/CB L-A',
                  children: [],
                },
                {
                  id: 5723,
                  parentId: 5720,
                  parent: 5720,
                  parentName: 'SEWING',
                  name: 'CB L-B',
                  rootPath: '/C. B. M. International Limited/SEWING/CB L-B',
                  children: [],
                },
                {
                  id: 5724,
                  parentId: 5720,
                  parent: 5720,
                  parentName: 'SEWING',
                  name: 'CB L-C',
                  rootPath: '/C. B. M. International Limited/SEWING/CB L-C',
                  children: [],
                },
                {
                  id: 5725,
                  parentId: 5720,
                  parent: 5720,
                  parentName: 'SEWING',
                  name: 'CB L-D',
                  rootPath: '/C. B. M. International Limited/SEWING/CB L-D',
                  children: [],
                },
                {
                  id: 5726,
                  parentId: 5720,
                  parent: 5720,
                  parentName: 'SEWING',
                  name: 'CB L-E',
                  rootPath: '/C. B. M. International Limited/SEWING/CB L-E',
                  children: [],
                },
                {
                  id: 5727,
                  parentId: 5720,
                  parent: 5720,
                  parentName: 'SEWING',
                  name: 'CB L-F',
                  rootPath: '/C. B. M. International Limited/SEWING/CB L-F',
                  children: [],
                },
                {
                  id: 5728,
                  parentId: 5720,
                  parent: 5720,
                  parentName: 'SEWING',
                  name: 'CB L-G',
                  rootPath: '/C. B. M. International Limited/SEWING/CB L-G',
                  children: [],
                },
                {
                  id: 5729,
                  parentId: 5720,
                  parent: 5720,
                  parentName: 'SEWING',
                  name: 'CB L-H',
                  rootPath: '/C. B. M. International Limited/SEWING/CB L-H',
                  children: [],
                },
                {
                  id: 5721,
                  parentId: 5720,
                  parent: 5720,
                  parentName: 'SEWING',
                  name: 'CB L-I',
                  rootPath: '/C. B. M. International Limited/SEWING/CB L-I',
                  children: [],
                },
              ],
            },
          ],
        },
        {
          id: 5602,
          parentId: 352,
          parent: 352,
          parentName: 'Root',
          name: 'Floor01',
          rootPath: '/Root/Floor01',
          children: [
            {
              id: 5604,
              parentId: 5602,
              parent: 5602,
              parentName: 'Floor01',
              name: 'Line 01',
              rootPath: '/Root/Floor01/Line 01',
              children: [],
            },
            {
              id: 5603,
              parentId: 5602,
              parent: 5602,
              parentName: 'Floor01',
              name: 'Line 0102',
              rootPath: '/Root/Floor01/Line 0102',
              children: [],
            },
          ],
        },
        {
          id: 5652,
          parentId: 352,
          parent: 352,
          parentName: 'Root',
          name: 'Gramtech Knit Dyeing Finishing n Garments Industries Ltd',
          rootPath: '/Gramtech Knit Dyeing Finishing n Garments Industries Ltd',
          children: [
            {
              id: 5681,
              parentId: 5652,
              parent: 5652,
              parentName:
                'Gramtech Knit Dyeing Finishing n Garments Industries Ltd',
              name: 'Sample',
              rootPath:
                '/Gramtech Knit Dyeing Finishing n Garments Industries Ltd/Sample',
              children: [
                {
                  id: 5682,
                  parentId: 5681,
                  parent: 5681,
                  parentName: 'Sample',
                  name: 'GT Pilot',
                  rootPath:
                    '/Gramtech Knit Dyeing Finishing n Garments Industries Ltd/Sample/GT Pilot',
                  children: [],
                },
              ],
            },
            {
              id: 5653,
              parentId: 5652,
              parent: 5652,
              parentName:
                'Gramtech Knit Dyeing Finishing n Garments Industries Ltd',
              name: 'Sewing U-1',
              rootPath:
                '/Gramtech Knit Dyeing Finishing n Garments Industries Ltd/Sewing U-1',
              children: [
                {
                  id: 6063,
                  parentId: 5653,
                  parent: 5653,
                  parentName: 'Sewing U-1',
                  name: 'Extra L-U1',
                  rootPath:
                    '/Gramtech Knit Dyeing Finishing n Garments Industries Ltd/Sewing U-1/Extra L-U1',
                  children: [],
                },
                {
                  id: 5654,
                  parentId: 5653,
                  parent: 5653,
                  parentName: 'Sewing U-1',
                  name: 'GT L01',
                  rootPath:
                    '/Gramtech Knit Dyeing Finishing n Garments Industries Ltd/Sewing U-1/GT L01',
                  children: [],
                },
                {
                  id: 5656,
                  parentId: 5653,
                  parent: 5653,
                  parentName: 'Sewing U-1',
                  name: 'GT L02',
                  rootPath:
                    '/Gramtech Knit Dyeing Finishing n Garments Industries Ltd/Sewing U-1/GT L02',
                  children: [],
                },
                {
                  id: 5657,
                  parentId: 5653,
                  parent: 5653,
                  parentName: 'Sewing U-1',
                  name: 'GT L03',
                  rootPath:
                    '/Gramtech Knit Dyeing Finishing n Garments Industries Ltd/Sewing U-1/GT L03',
                  children: [],
                },
                {
                  id: 5826,
                  parentId: 5653,
                  parent: 5653,
                  parentName: 'Sewing U-1',
                  name: 'GT L04',
                  rootPath:
                    '/Gramtech Knit Dyeing Finishing n Garments Industries Ltd/Sewing U-1/GT L04',
                  children: [],
                },
                {
                  id: 5658,
                  parentId: 5653,
                  parent: 5653,
                  parentName: 'Sewing U-1',
                  name: 'GT L05',
                  rootPath:
                    '/Gramtech Knit Dyeing Finishing n Garments Industries Ltd/Sewing U-1/GT L05',
                  children: [],
                },
                {
                  id: 5659,
                  parentId: 5653,
                  parent: 5653,
                  parentName: 'Sewing U-1',
                  name: 'GT L06',
                  rootPath:
                    '/Gramtech Knit Dyeing Finishing n Garments Industries Ltd/Sewing U-1/GT L06',
                  children: [],
                },
                {
                  id: 5660,
                  parentId: 5653,
                  parent: 5653,
                  parentName: 'Sewing U-1',
                  name: 'GT L07',
                  rootPath:
                    '/Gramtech Knit Dyeing Finishing n Garments Industries Ltd/Sewing U-1/GT L07',
                  children: [],
                },
                {
                  id: 5661,
                  parentId: 5653,
                  parent: 5653,
                  parentName: 'Sewing U-1',
                  name: 'GT L08',
                  rootPath:
                    '/Gramtech Knit Dyeing Finishing n Garments Industries Ltd/Sewing U-1/GT L08',
                  children: [],
                },
                {
                  id: 5662,
                  parentId: 5653,
                  parent: 5653,
                  parentName: 'Sewing U-1',
                  name: 'GT L09',
                  rootPath:
                    '/Gramtech Knit Dyeing Finishing n Garments Industries Ltd/Sewing U-1/GT L09',
                  children: [],
                },
                {
                  id: 6053,
                  parentId: 5653,
                  parent: 5653,
                  parentName: 'Sewing U-1',
                  name: 'GT L10',
                  rootPath:
                    '/Gramtech Knit Dyeing Finishing n Garments Industries Ltd/Sewing U-1/GT L10',
                  children: [],
                },
                {
                  id: 6052,
                  parentId: 5653,
                  parent: 5653,
                  parentName: 'Sewing U-1',
                  name: 'GT L11',
                  rootPath:
                    '/Gramtech Knit Dyeing Finishing n Garments Industries Ltd/Sewing U-1/GT L11',
                  children: [],
                },
                {
                  id: 5655,
                  parentId: 5653,
                  parent: 5653,
                  parentName: 'Sewing U-1',
                  name: 'GT L12',
                  rootPath:
                    '/Gramtech Knit Dyeing Finishing n Garments Industries Ltd/Sewing U-1/GT L12',
                  children: [],
                },
              ],
            },
            {
              id: 5663,
              parentId: 5652,
              parent: 5652,
              parentName:
                'Gramtech Knit Dyeing Finishing n Garments Industries Ltd',
              name: 'Sewing U-2',
              rootPath:
                '/Gramtech Knit Dyeing Finishing n Garments Industries Ltd/Sewing U-2',
              children: [
                {
                  id: 6061,
                  parentId: 5663,
                  parent: 5663,
                  parentName: 'Sewing U-2',
                  name: 'Extra L-U2',
                  rootPath:
                    '/Gramtech Knit Dyeing Finishing n Garments Industries Ltd/Sewing U-2/Extra L-U2',
                  children: [],
                },
                {
                  id: 5664,
                  parentId: 5663,
                  parent: 5663,
                  parentName: 'Sewing U-2',
                  name: 'GT L13',
                  rootPath:
                    '/Gramtech Knit Dyeing Finishing n Garments Industries Ltd/Sewing U-2/GT L13',
                  children: [],
                },
                {
                  id: 6054,
                  parentId: 5663,
                  parent: 5663,
                  parentName: 'Sewing U-2',
                  name: 'GT L14',
                  rootPath:
                    '/Gramtech Knit Dyeing Finishing n Garments Industries Ltd/Sewing U-2/GT L14',
                  children: [],
                },
                {
                  id: 5665,
                  parentId: 5663,
                  parent: 5663,
                  parentName: 'Sewing U-2',
                  name: 'GT L15',
                  rootPath:
                    '/Gramtech Knit Dyeing Finishing n Garments Industries Ltd/Sewing U-2/GT L15',
                  children: [],
                },
                {
                  id: 5666,
                  parentId: 5663,
                  parent: 5663,
                  parentName: 'Sewing U-2',
                  name: 'GT L16',
                  rootPath:
                    '/Gramtech Knit Dyeing Finishing n Garments Industries Ltd/Sewing U-2/GT L16',
                  children: [],
                },
                {
                  id: 6062,
                  parentId: 5663,
                  parent: 5663,
                  parentName: 'Sewing U-2',
                  name: 'GT L17',
                  rootPath:
                    '/Gramtech Knit Dyeing Finishing n Garments Industries Ltd/Sewing U-2/GT L17',
                  children: [],
                },
                {
                  id: 5667,
                  parentId: 5663,
                  parent: 5663,
                  parentName: 'Sewing U-2',
                  name: 'GT L18',
                  rootPath:
                    '/Gramtech Knit Dyeing Finishing n Garments Industries Ltd/Sewing U-2/GT L18',
                  children: [],
                },
                {
                  id: 6058,
                  parentId: 5663,
                  parent: 5663,
                  parentName: 'Sewing U-2',
                  name: 'GT L19',
                  rootPath:
                    '/Gramtech Knit Dyeing Finishing n Garments Industries Ltd/Sewing U-2/GT L19',
                  children: [],
                },
                {
                  id: 5668,
                  parentId: 5663,
                  parent: 5663,
                  parentName: 'Sewing U-2',
                  name: 'GT L20',
                  rootPath:
                    '/Gramtech Knit Dyeing Finishing n Garments Industries Ltd/Sewing U-2/GT L20',
                  children: [],
                },
                {
                  id: 5669,
                  parentId: 5663,
                  parent: 5663,
                  parentName: 'Sewing U-2',
                  name: 'GT L21',
                  rootPath:
                    '/Gramtech Knit Dyeing Finishing n Garments Industries Ltd/Sewing U-2/GT L21',
                  children: [],
                },
                {
                  id: 5670,
                  parentId: 5663,
                  parent: 5663,
                  parentName: 'Sewing U-2',
                  name: 'GT L22',
                  rootPath:
                    '/Gramtech Knit Dyeing Finishing n Garments Industries Ltd/Sewing U-2/GT L22',
                  children: [],
                },
                {
                  id: 5671,
                  parentId: 5663,
                  parent: 5663,
                  parentName: 'Sewing U-2',
                  name: 'GT L23',
                  rootPath:
                    '/Gramtech Knit Dyeing Finishing n Garments Industries Ltd/Sewing U-2/GT L23',
                  children: [],
                },
                {
                  id: 6055,
                  parentId: 5663,
                  parent: 5663,
                  parentName: 'Sewing U-2',
                  name: 'GT L24',
                  rootPath:
                    '/Gramtech Knit Dyeing Finishing n Garments Industries Ltd/Sewing U-2/GT L24',
                  children: [],
                },
              ],
            },
            {
              id: 5672,
              parentId: 5652,
              parent: 5652,
              parentName:
                'Gramtech Knit Dyeing Finishing n Garments Industries Ltd',
              name: 'Sewing U-3',
              rootPath:
                '/Gramtech Knit Dyeing Finishing n Garments Industries Ltd/Sewing U-3',
              children: [
                {
                  id: 6059,
                  parentId: 5672,
                  parent: 5672,
                  parentName: 'Sewing U-3',
                  name: 'Extra L-U3',
                  rootPath:
                    '/Gramtech Knit Dyeing Finishing n Garments Industries Ltd/Sewing U-3/Extra L-U3',
                  children: [],
                },
                {
                  id: 6064,
                  parentId: 5672,
                  parent: 5672,
                  parentName: 'Sewing U-3',
                  name: 'GT L25',
                  rootPath:
                    '/Gramtech Knit Dyeing Finishing n Garments Industries Ltd/Sewing U-3/GT L25',
                  children: [],
                },
                {
                  id: 5673,
                  parentId: 5672,
                  parent: 5672,
                  parentName: 'Sewing U-3',
                  name: 'GT L26',
                  rootPath:
                    '/Gramtech Knit Dyeing Finishing n Garments Industries Ltd/Sewing U-3/GT L26',
                  children: [],
                },
                {
                  id: 6060,
                  parentId: 5672,
                  parent: 5672,
                  parentName: 'Sewing U-3',
                  name: 'GT L27',
                  rootPath:
                    '/Gramtech Knit Dyeing Finishing n Garments Industries Ltd/Sewing U-3/GT L27',
                  children: [],
                },
                {
                  id: 5674,
                  parentId: 5672,
                  parent: 5672,
                  parentName: 'Sewing U-3',
                  name: 'GT L28',
                  rootPath:
                    '/Gramtech Knit Dyeing Finishing n Garments Industries Ltd/Sewing U-3/GT L28',
                  children: [],
                },
                {
                  id: 5675,
                  parentId: 5672,
                  parent: 5672,
                  parentName: 'Sewing U-3',
                  name: 'GT L29',
                  rootPath:
                    '/Gramtech Knit Dyeing Finishing n Garments Industries Ltd/Sewing U-3/GT L29',
                  children: [],
                },
                {
                  id: 5676,
                  parentId: 5672,
                  parent: 5672,
                  parentName: 'Sewing U-3',
                  name: 'GT L30',
                  rootPath:
                    '/Gramtech Knit Dyeing Finishing n Garments Industries Ltd/Sewing U-3/GT L30',
                  children: [],
                },
                {
                  id: 5677,
                  parentId: 5672,
                  parent: 5672,
                  parentName: 'Sewing U-3',
                  name: 'GT L31',
                  rootPath:
                    '/Gramtech Knit Dyeing Finishing n Garments Industries Ltd/Sewing U-3/GT L31',
                  children: [],
                },
                {
                  id: 5678,
                  parentId: 5672,
                  parent: 5672,
                  parentName: 'Sewing U-3',
                  name: 'GT L32',
                  rootPath:
                    '/Gramtech Knit Dyeing Finishing n Garments Industries Ltd/Sewing U-3/GT L32',
                  children: [],
                },
                {
                  id: 5679,
                  parentId: 5672,
                  parent: 5672,
                  parentName: 'Sewing U-3',
                  name: 'GT L33',
                  rootPath:
                    '/Gramtech Knit Dyeing Finishing n Garments Industries Ltd/Sewing U-3/GT L33',
                  children: [],
                },
                {
                  id: 6056,
                  parentId: 5672,
                  parent: 5672,
                  parentName: 'Sewing U-3',
                  name: 'GT L34',
                  rootPath:
                    '/Gramtech Knit Dyeing Finishing n Garments Industries Ltd/Sewing U-3/GT L34',
                  children: [],
                },
                {
                  id: 6057,
                  parentId: 5672,
                  parent: 5672,
                  parentName: 'Sewing U-3',
                  name: 'GT L35',
                  rootPath:
                    '/Gramtech Knit Dyeing Finishing n Garments Industries Ltd/Sewing U-3/GT L35',
                  children: [],
                },
                {
                  id: 5680,
                  parentId: 5672,
                  parent: 5672,
                  parentName: 'Sewing U-3',
                  name: 'GT L36',
                  rootPath:
                    '/Gramtech Knit Dyeing Finishing n Garments Industries Ltd/Sewing U-3/GT L36',
                  children: [],
                },
              ],
            },
          ],
        },
        {
          id: 1302,
          parentId: 352,
          parent: 352,
          parentName: 'Root',
          name: 'Line 0301 Org org',
          rootPath: '/Root/Line 0301 Org org',
          children: [],
        },
        {
          id: 1352,
          parentId: 352,
          parent: 352,
          parentName: 'Root',
          name: 'Line 0401 org',
          rootPath: '/Root/Unit-1/Line 0401',
          children: [],
        },
        {
          id: 1353,
          parentId: 352,
          parent: 352,
          parentName: 'Root',
          name: 'Line 0403 org',
          rootPath: '/Root/Unit-1/Line 0403',
          children: [],
        },
        {
          id: 1256,
          parentId: 352,
          parent: 352,
          parentName: 'Root',
          name: 'Line-0201 org',
          rootPath: '/Root/Unit-1/Line-0201',
          children: [],
        },
        {
          id: 1255,
          parentId: 352,
          parent: 352,
          parentName: 'Root',
          name: 'Line0102 Or',
          rootPath: '/Root/Line0102 Or',
          children: [],
        },
        {
          id: 5683,
          parentId: 352,
          parent: 352,
          parentName: 'Root',
          name: 'Mars Stitch Ltd.',
          rootPath: '/Mars Stitch Ltd.',
          children: [
            {
              id: 5694,
              parentId: 5683,
              parent: 5683,
              parentName: 'Mars Stitch Ltd.',
              name: '3RD FLOOR',
              rootPath: '/Mars Stitch Ltd./3RD FLOOR',
              children: [
                {
                  id: 5695,
                  parentId: 5694,
                  parent: 5694,
                  parentName: '3RD FLOOR',
                  name: 'MS L09',
                  rootPath: '/Mars Stitch Ltd./3RD FLOOR/MS L09',
                  children: [],
                },
                {
                  id: 5696,
                  parentId: 5694,
                  parent: 5694,
                  parentName: '3RD FLOOR',
                  name: 'MS L10',
                  rootPath: '/Mars Stitch Ltd./3RD FLOOR/MS L10',
                  children: [],
                },
                {
                  id: 5697,
                  parentId: 5694,
                  parent: 5694,
                  parentName: '3RD FLOOR',
                  name: 'MS L11',
                  rootPath: '/Mars Stitch Ltd./3RD FLOOR/MS L11',
                  children: [],
                },
                {
                  id: 5698,
                  parentId: 5694,
                  parent: 5694,
                  parentName: '3RD FLOOR',
                  name: 'MS L12',
                  rootPath: '/Mars Stitch Ltd./3RD FLOOR/MS L12',
                  children: [],
                },
              ],
            },
            {
              id: 5689,
              parentId: 5683,
              parent: 5683,
              parentName: 'Mars Stitch Ltd.',
              name: '4TH FLOOR',
              rootPath: '/Mars Stitch Ltd./4TH FLOOR',
              children: [
                {
                  id: 5690,
                  parentId: 5689,
                  parent: 5689,
                  parentName: '4TH FLOOR',
                  name: 'MS L05',
                  rootPath: '/Mars Stitch Ltd./4TH FLOOR/MS L05',
                  children: [],
                },
                {
                  id: 5691,
                  parentId: 5689,
                  parent: 5689,
                  parentName: '4TH FLOOR',
                  name: 'MS L06',
                  rootPath: '/Mars Stitch Ltd./4TH FLOOR/MS L06',
                  children: [],
                },
                {
                  id: 5692,
                  parentId: 5689,
                  parent: 5689,
                  parentName: '4TH FLOOR',
                  name: 'MS L07',
                  rootPath: '/Mars Stitch Ltd./4TH FLOOR/MS L07',
                  children: [],
                },
                {
                  id: 5693,
                  parentId: 5689,
                  parent: 5689,
                  parentName: '4TH FLOOR',
                  name: 'MS L08',
                  rootPath: '/Mars Stitch Ltd./4TH FLOOR/MS L08',
                  children: [],
                },
              ],
            },
            {
              id: 5684,
              parentId: 5683,
              parent: 5683,
              parentName: 'Mars Stitch Ltd.',
              name: '5TH FLOOR',
              rootPath: '/Mars Stitch Ltd./5TH FLOOR',
              children: [
                {
                  id: 5685,
                  parentId: 5684,
                  parent: 5684,
                  parentName: '5TH FLOOR',
                  name: 'MS L01',
                  rootPath: '/Mars Stitch Ltd./5TH FLOOR/MS L01',
                  children: [],
                },
                {
                  id: 5686,
                  parentId: 5684,
                  parent: 5684,
                  parentName: '5TH FLOOR',
                  name: 'MS L02',
                  rootPath: '/Mars Stitch Ltd./5TH FLOOR/MS L02',
                  children: [],
                },
                {
                  id: 5687,
                  parentId: 5684,
                  parent: 5684,
                  parentName: '5TH FLOOR',
                  name: 'MS L03',
                  rootPath: '/Mars Stitch Ltd./5TH FLOOR/MS L03',
                  children: [],
                },
                {
                  id: 5688,
                  parentId: 5684,
                  parent: 5684,
                  parentName: '5TH FLOOR',
                  name: 'MS L04',
                  rootPath: '/Mars Stitch Ltd./5TH FLOOR/MS L04',
                  children: [],
                },
              ],
            },
          ],
        },
        {
          id: 1753,
          parentId: 352,
          parent: 352,
          parentName: 'Root',
          name: 'myh_ln1',
          rootPath: '/Root/myh_ln1',
          children: [],
        },
        {
          id: 1754,
          parentId: 352,
          parent: 352,
          parentName: 'Root',
          name: 'myh_ln2',
          rootPath: '/Root/myh_ln2',
          children: [],
        },
        {
          id: 1755,
          parentId: 352,
          parent: 352,
          parentName: 'Root',
          name: 'myh_ln3',
          rootPath: '/Root/myh_ln3',
          children: [],
        },
        {
          id: 1756,
          parentId: 352,
          parent: 352,
          parentName: 'Root',
          name: 'myh_ln4',
          rootPath: '/Root/myh_ln4',
          children: [],
        },
        {
          id: 2052,
          parentId: 352,
          parent: 352,
          parentName: 'Root',
          name: 'myh_unit',
          rootPath: '/Root/myh_unit',
          children: [
            {
              id: 1905,
              parentId: 2052,
              parent: 2052,
              parentName: 'myh_unit',
              name: 'myh_ln5',
              rootPath: '/Root/myh_ln5',
              children: [],
            },
          ],
        },
        {
          id: 805,
          parentId: 352,
          parent: 352,
          parentName: 'Root',
          name: 'N200',
          rootPath: '/Root/N200',
          children: [],
        },
        {
          id: 752,
          parentId: 352,
          parent: 352,
          parentName: 'Root',
          name: 'New10',
          rootPath: '/Root/New10',
          children: [],
        },
        {
          id: 753,
          parentId: 352,
          parent: 352,
          parentName: 'Root',
          name: 'New11',
          rootPath: '/Root/New11',
          children: [],
        },
        {
          id: 754,
          parentId: 352,
          parent: 352,
          parentName: 'Root',
          name: 'New12',
          rootPath: '/Root/New12',
          children: [],
        },
        {
          id: 755,
          parentId: 352,
          parent: 352,
          parentName: 'Root',
          name: 'New13',
          rootPath: '/Root/New13',
          children: [],
        },
        {
          id: 756,
          parentId: 352,
          parent: 352,
          parentName: 'Root',
          name: 'New14',
          rootPath: '/Root/New14',
          children: [
            {
              id: 2003,
              parentId: 756,
              parent: 756,
              parentName: 'New14',
              name: 'Toot toot org',
              rootPath: '/Root/New14/Toot toot org',
              children: [],
            },
          ],
        },
        {
          id: 757,
          parentId: 352,
          parent: 352,
          parentName: 'Root',
          name: 'New15',
          rootPath: '/Root/New15',
          children: [],
        },
        {
          id: 758,
          parentId: 352,
          parent: 352,
          parentName: 'Root',
          name: 'New16',
          rootPath: '/Root/New16',
          children: [],
        },
        {
          id: 759,
          parentId: 352,
          parent: 352,
          parentName: 'Root',
          name: 'New17',
          rootPath: '/Root/New17',
          children: [],
        },
        {
          id: 760,
          parentId: 352,
          parent: 352,
          parentName: 'Root',
          name: 'New18',
          rootPath: '/Root/New18',
          children: [],
        },
        {
          id: 761,
          parentId: 352,
          parent: 352,
          parentName: 'Root',
          name: 'New19',
          rootPath: '/Root/New19',
          children: [],
        },
        {
          id: 762,
          parentId: 352,
          parent: 352,
          parentName: 'Root',
          name: 'New20',
          rootPath: '/Root/New20',
          children: [],
        },
        {
          id: 763,
          parentId: 352,
          parent: 352,
          parentName: 'Root',
          name: 'New21',
          rootPath: '/Root/New21',
          children: [],
        },
        {
          id: 764,
          parentId: 352,
          parent: 352,
          parentName: 'Root',
          name: 'New22',
          rootPath: '/Root/New22',
          children: [],
        },
        {
          id: 765,
          parentId: 352,
          parent: 352,
          parentName: 'Root',
          name: 'New23',
          rootPath: '/Root/New23',
          children: [],
        },
        {
          id: 766,
          parentId: 352,
          parent: 352,
          parentName: 'Root',
          name: 'New24',
          rootPath: '/Root/New24',
          children: [],
        },
        {
          id: 6603,
          parentId: 352,
          parent: 352,
          parentName: 'Root',
          name: 'Order Status',
          rootPath: '/Root/Order Status',
          children: [
            {
              id: 6604,
              parentId: 6603,
              parent: 6603,
              parentName: 'Order Status',
              name: 'Order Line 01',
              rootPath: '/Root/Order Status/Order Line 01',
              children: [],
            },
          ],
        },
        {
          id: 2054,
          parentId: 352,
          parent: 352,
          parentName: 'Root',
          name: 'org test',
          rootPath: '/Root/org test',
          children: [],
        },
        {
          id: 602,
          parentId: 352,
          parent: 352,
          parentName: 'Root',
          name: 'QC_test',
          rootPath: '/Root/Unit-1/QC_test',
          children: [],
        },
        {
          id: 6552,
          parentId: 352,
          parent: 352,
          parentName: 'Root',
          name: 'Subhro Yearn Ltd. ',
          rootPath: '/Root/Subhro Yearn Ltd. ',
          children: [],
        },
        {
          id: 1952,
          parentId: 352,
          parent: 352,
          parentName: 'Root',
          name: 'test 1000',
          rootPath: '/Root/test 1000',
          children: [],
        },
        {
          id: 6004,
          parentId: 352,
          parent: 352,
          parentName: 'Root',
          name: 'Test 12341',
          rootPath: '/Root/Test 12341',
          children: [],
        },
        {
          id: 552,
          parentId: 352,
          parent: 352,
          parentName: 'Root',
          name: 'Test1',
          rootPath: '/Root/Test1',
          children: [],
        },
        {
          id: 802,
          parentId: 352,
          parent: 352,
          parentName: 'Root',
          name: 'Test1000',
          rootPath: '/Root/Test1000',
          children: [],
        },
        {
          id: 803,
          parentId: 352,
          parent: 352,
          parentName: 'Root',
          name: 'Test999',
          rootPath: '/Root/Test999',
          children: [],
        },
        {
          id: 1752,
          parentId: 352,
          parent: 352,
          parentName: 'Root',
          name: 'testCheck',
          rootPath: '/Root/testCheck',
          children: [],
        },
        {
          id: 1152,
          parentId: 352,
          parent: 352,
          parentName: 'Root',
          name: 'Unit-1',
          rootPath: '/Root/Unit-1',
          children: [
            {
              id: 1902,
              parentId: 1152,
              parent: 1152,
              parentName: 'Unit-1',
              name: 'App Test',
              rootPath: '/Root/Unit-1/App Test',
              children: [],
            },
            {
              id: 1904,
              parentId: 1152,
              parent: 1152,
              parentName: 'Unit-1',
              name: 'App Test 12',
              rootPath: '/Root/Unit-1/App Test 12',
              children: [],
            },
            {
              id: 1052,
              parentId: 1152,
              parent: 1152,
              parentName: 'Unit-1',
              name: 'Line-03',
              rootPath: '/Root/Line-03',
              children: [],
            },
            {
              id: 652,
              parentId: 1152,
              parent: 1152,
              parentName: 'Unit-1',
              name: 'Riaz Test',
              rootPath: '/Root/Riaz Test',
              children: [],
            },
            {
              id: 1253,
              parentId: 1152,
              parent: 1152,
              parentName: 'Unit-1',
              name: 'sync',
              rootPath: '/Root/Unit-1/sync',
              children: [],
            },
            {
              id: 1254,
              parentId: 1152,
              parent: 1152,
              parentName: 'Unit-1',
              name: 'Sync 12',
              rootPath: '/Root/Unit-1/Sync 1',
              children: [],
            },
            {
              id: 1252,
              parentId: 1152,
              parent: 1152,
              parentName: 'Unit-1',
              name: 'Sync Test',
              rootPath: '/Root/Unit-1/Sync Test',
              children: [],
            },
            {
              id: 553,
              parentId: 1152,
              parent: 1152,
              parentName: 'Unit-1',
              name: 'Test New',
              rootPath: '/Root/Unit-1/Test New',
              children: [],
            },
          ],
        },
        {
          id: 2053,
          parentId: 352,
          parent: 352,
          parentName: 'Root',
          name: 'Update Test Org1',
          rootPath: '/Root/App QC Test 1',
          children: [],
        },
        {
          id: 1903,
          parentId: 352,
          parent: 352,
          parentName: 'Root',
          name: 'Update Test Org2',
          rootPath: '/Root/App Test 101',
          children: [],
        },
        {
          id: 1953,
          parentId: 352,
          parent: 352,
          parentName: 'Root',
          name: 'Update Test Org3',
          rootPath: '/Root/app test 121',
          children: [],
        },
        {
          id: 767,
          parentId: 352,
          parent: 352,
          parentName: 'Root',
          name: 'Zoo',
          rootPath: '/Root/Zoo',
          children: [
            {
              id: 804,
              parentId: 767,
              parent: 767,
              parentName: 'Zoo',
              name: 'N110',
              rootPath: '/Root/Zoo/N110',
              children: [],
            },
          ],
        },
      ],
    },
  ];

  const testData = [
    {
      color: 'White',
      size: 'M',
      inputQty: 1000,
      qcQty: 900,
      totalReceive: 500,
      balanceQty: 500,
      receiveQty: 0,
    },
    {
      color: 'Black',
      size: 'L',
      inputQty: 2000,
      qcQty: 1900,
      totalReceive: 1000,
      balanceQty: 1000,
      receiveQty: 0,
    },
  ];

  const renderItem = ({item}: {item: number}) => (
    <DataTableComponent
      buyer="Buyer"
      buyerName="Brothers Fashion Ltd."
      style="Style"
      styleName="Brother-5060OD"
      order="PO"
      orderNumber="PO-5623147855"
      showCheckbox={true}
      columnNames={[
        'Color',
        'Size',
        'Input Qty.',
        'QC Qty.',
        'Total Receive',
        'Balance Qty.',
        'Receive Qty.',
      ]}
      rowData={testData}
    />
  );

  return (
    <View style={{backgroundColor: 'white', flex: 1}}>
      <CustomModalButton
        buttonStyle={Styles.selectLineDateButton}
        buttonTextStyle={Styles.selectLineDateButtonText}
        onPress={() => setLineModalVisible(true)}
        text={selectedLine !== '' ? selectedLine : 'Select Line'}
        icon={<Icon name="caret-down" size={25} color="#1C98D8" />}
      />
      {/* Modal for TreeSelect */}
      <SelectLineModal
        orgTreeData={orgTreeData}
        setSelectedLine={setSelectedLine}
        lineModalVisible={lineModalVisible}
        setLineModalVisible={setLineModalVisible}
      />
      <FlatList
        style={{marginBottom: 100}}
        data={[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]}
        renderItem={renderItem}
        keyExtractor={(item, index) => index.toString()}
      />
      <CustomSubmitButton
        icon={<Icon name="tencent-weibo" size={20} color={'white'} />}
        text="CONFIRM RECEIVE"
      />
    </View>
  );
};

export default ReceiveTab;
